swift 3 migration
xmartlabs/XLSlidingContainer pull request #4
Opened 2017-03-09 14:16 UTC by mcousillas6

Swift 3 migration:

* Updated the codebase to Swift3.
* Updated the readme to match new code.
* Added podspec and cartfile with new version (2.0.0)
* Added new example project.

2017-03-09 15:03 UTC, m-revetria requested changes

2017-03-09 15:03 UTC, m-revetria commented on CHANGELOG.md
> +### [1.0.0](https://github.com/xmartlabs/XLSlidingContainer/releases/tag/1.0.0)
please reorder the change log to newest releases first

2017-03-09 15:03 UTC, m-revetria commented on Example/Example/ViewController.swift
> +    func upperViewMin(for slidingContainer: SlidingContainerViewController) -> CGFloat {
min what? I would rename this function to be more descriptive

2017-03-09 15:03 UTC, m-revetria commented on Example/Example/ViewController.swift
> +    func lowerViewMin(for slidingContainer: SlidingContainerViewController) -> CGFloat {
same here

2017-03-09 15:03 UTC, m-revetria commented on SlidingContainer.podspec
> +  s.summary          = "A short description of SlidingContainer."
please add a description

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    func upperViewMin(for slidingContainer: SlidingContainerViewController) -> CGFloat
min what? I would rename this function to be more descriptive

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    func lowerViewMin(for slidingContainer: SlidingContainerViewController) -> CGFloat
same here

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +        navView = navView == nil ? view : navView
`navView = navView ?? view`?

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +        dragView = dragView == nil ? dView : dragView
you can use `??` here as well

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +        let dragHeight = (dragView?.frame.height ?? 42)
maybe you can move `42` to a constant or all this `dragView?.frame.height ?? 42` to a property, what do you think?

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +                f1.origin.y  += translation.y
please delete extra space in `y  +`

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +
please delete this line

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +                    let navHeight = navView?.frame.height,
please move all the condition of this `if` to an auxiliar function and reuse it from everywhere

2017-03-09 15:03 UTC, m-revetria commented on Tests/SlidingContainerTests.swift
> +//  Copyright © 2016 Xmartlabs SRL. All rights reserved.
Copyright © **2017**

2017-03-09 15:03 UTC, m-revetria commented on Example/Example.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
could you please add swiftlint to the project?

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
`public` vs `open`, thoughts?

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    func reloadLowerViewController() {
i think these two `reload...` functions should be public, they used to be

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    func getMovementDifference() -> CGFloat {
I think this can be private/fileprivate, please review the functions defined here and let everything that can be private as private

2017-03-09 15:03 UTC, m-revetria commented on Sources/SlidingContainerViewController.swift
> +    public var upperController: ContainedViewController!
I think this should be private or at least its setter should. Same concern with the non-private properties below

2017-03-09 15:26 UTC, santiagofm commented on Example/Example/CollectionViewController.swift
> +    func updateFrameFor(heightPercentaje yPct: CGFloat, absolute diff: CGFloat) { }
delete this unused method

2017-03-09 15:26 UTC, santiagofm commented on Example/Example/MyImageCollectionViewCell.swift
> +        imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: self.frame.size.width, height: self.frame.size.height))
Please use bounds instead of frame

2017-03-09 15:26 UTC, santiagofm commented on Example/Example/ScrollViewController.swift
> +        let scrollView = UIScrollView();
Maybe move this code to the `viewDidLoad` method

2017-03-09 15:26 UTC, santiagofm commented on Example/Example/ScrollViewController.swift
> +    func updateFrameFor(heightPercentaje yPct: CGFloat, absolute diff: CGFloat) { }
Remove unused methods please

2017-03-09 15:26 UTC, santiagofm commented on Example/Example/ViewController.swift
> +
Remove unused methods please

2017-03-09 15:26 UTC, santiagofm commented on SlidingContainer.podspec
> +  s.source           = { git: "https://github.com/xmartlabs/SlidingContainer.git", tag: s.version.to_s }
Shouldn't it be `XLSlidingContainer` ?

2017-03-09 15:26 UTC, santiagofm commented on Sources/SlidingContainerViewController.swift
> +    func slidingContainerDidBeingDrag(_ slidingContainer: SlidingContainerViewController)
Fix typo

2017-03-09 15:26 UTC, santiagofm commented on Sources/SlidingContainerViewController.swift
> +        if !frame.contains(location) && !isDragging {
please use a `guard`

2017-03-09 16:28 UTC, mats-claassen approved these changes

2017-03-09 17:04 UTC, mcousillas6 commented on Sources/SlidingContainerViewController.swift
> +    public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
Let's leave it open, that way the user can decide when the sliding is active

2017-03-10 14:44 UTC, m-revetria approved these changes

2017-03-13 17:27 UTC, merged